nifty50 = [
    # Original 25
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "KOTAKBANK.NS", "SBIN.NS", "ITC.NS", "LT.NS", "AXISBANK.NS",
    "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS", "BAJFINANCE.NS",
    "BHARTIARTL.NS", "HCLTECH.NS", "TITAN.NS", "ULTRACEMCO.NS",
    "NESTLEIND.NS", "WIPRO.NS", "ADANIENT.NS", "TATASTEEL.NS",
    "ONGC.NS", "POWERGRID.NS", "NTPC.NS",

    # Remaining Nifty 50 constituents
    "ADANIPORTS.NS", "APOLLOHOSP.NS", "BAJAJ-AUTO.NS", "BAJAJFINSV.NS",
    "BPCL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS",
    "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS",
    "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS",
    "INDUSINDBK.NS", "JSWSTEEL.NS", "M&M.NS", "SBILIFE.NS",
    "SHRIRAMFIN.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TECHM.NS",
    "TRENT.NS",
]
